# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeSports' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeSports
pod 'DropDown'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'RangeSeekSlider'

end
